// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1_Ap2.DAL;

namespace Parcial1_Ap2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200611012141_CreateProductoDb")]
    partial class CreateProductoDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Parcial1_Ap2.Models.Producto", b =>
                {
                    b.Property<int>("productoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<int>("existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valorInventario")
                        .HasColumnType("TEXT");

                    b.HasKey("productoId");

                    b.ToTable("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
